@echo off
docker run -p 5000:8080 -u root -e ASPNETCORE_HTTP_PORTS=8080 ^
-e OTEL_TRACES_EXPORTER=none ^
-e OTEL_METRICS_EXPORTER=none ^
-e OTEL_LOGS_EXPORTER=none ^
-e OTEL_DOTNET_AUTO_TRACES_CONSOLE_EXPORTER_ENABLED=true ^
-e OTEL_DOTNET_AUTO_METRICS_CONSOLE_EXPORTER_ENABLED=true ^
-e OTEL_DOTNET_AUTO_LOGS_CONSOLE_EXPORTER_ENABLED=true ^
-e OTEL_SERVICE_NAME=csharpsample ^
csharpsample